/**
 * WASM SIMD Bridge — browser-side acceleration layer
 *
 * This module loads the Rust-compiled WASM module (native-wasm) inside
 * Web Workers and provides the same API surface as nativeBridge.ts.
 *
 * Priority chain:
 *   1. Native (napi-rs, Node.js side) — fastest, mmap access
 *   2. WASM SIMD (this module, browser Worker) — fast, SIMD128 accelerated
 *   3. Pure JS fallback (nativeBridge.ts fallbacks) — slowest
 */

export interface WasmBindings {
  parseHeader(data: Uint8Array): any | null;
  extractSlice(data: Uint8Array, headerJson: string, axis: string, index: number): Float32Array | null;
  extractPreview(data: Uint8Array): { header: any; axial: Float32Array; coronal: Float32Array; sagittal: Float32Array; min: number; max: number } | null;
  applyWindowLevel(data: Float32Array, windowLevel: number, windowWidth: number, globalMin: number, globalMax: number): Uint8Array;
  resampleSlice(data: Float32Array, srcWidth: number, srcHeight: number, dstWidth: number, dstHeight: number): Float32Array;
  getVolumeStats(data: Uint8Array, headerJson: string): { min: number; max: number; mean: number; std: number; p1: number; p5: number; p95: number; p99: number; histogram: number[] } | null;
  hasSimd(): boolean;
}

let wasmInstance: WasmBindings | null | undefined; // undefined = not attempted, null = failed

// Base64 decoder for preview data
function base64Decode(s: string): Uint8Array {
  const bin = atob(s);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) {
    bytes[i] = bin.charCodeAt(i);
  }
  return bytes;
}

function bytesToFloat32(bytes: Uint8Array): Float32Array {
  return new Float32Array(bytes.buffer, bytes.byteOffset, bytes.byteLength / 4);
}

function wrapWasmExports(exports: any): WasmBindings {
  return {
    parseHeader(data: Uint8Array): any | null {
      const json = exports.wasm_parse_header(data);
      return json ? JSON.parse(json) : null;
    },

    extractSlice(data: Uint8Array, headerJson: string, axis: string, index: number): Float32Array | null {
      const bytes = exports.wasm_extract_slice(data, headerJson, axis, index);
      return bytes ? bytesToFloat32(new Uint8Array(bytes)) : null;
    },

    extractPreview(data: Uint8Array) {
      const json = exports.wasm_extract_preview(data);
      if (!json) return null;
      const result = JSON.parse(json);
      return {
        header: result.header,
        axial: bytesToFloat32(base64Decode(result.axial.data)),
        coronal: bytesToFloat32(base64Decode(result.coronal.data)),
        sagittal: bytesToFloat32(base64Decode(result.sagittal.data)),
        min: result.min,
        max: result.max,
      };
    },

    applyWindowLevel(data: Float32Array, windowLevel: number, windowWidth: number, globalMin: number, globalMax: number): Uint8Array {
      return new Uint8Array(exports.wasm_apply_window_level(data, windowLevel, windowWidth, globalMin, globalMax));
    },

    resampleSlice(data: Float32Array, srcWidth: number, srcHeight: number, dstWidth: number, dstHeight: number): Float32Array {
      const bytes = exports.wasm_resample_slice(data, srcWidth, srcHeight, dstWidth, dstHeight);
      return bytesToFloat32(new Uint8Array(bytes));
    },

    getVolumeStats(data: Uint8Array, headerJson: string) {
      const json = exports.wasm_get_volume_stats(data, headerJson);
      if (!json) return null;
      return JSON.parse(json);
    },

    hasSimd(): boolean {
      return exports.wasm_has_simd();
    },
  };
}

/**
 * Initialize the WASM module. Must be called once before using any function.
 * Returns the bindings object or null if WASM is unavailable.
 */
export async function initWasmBindings(): Promise<WasmBindings | null> {
  if (wasmInstance !== undefined) return wasmInstance;

  try {
    // Dynamic import of the WASM module generated by wasm-pack
    // The module is located at webview/wasm/ after build
    const wasmModule = await import('./wasm/niftispy_wasm');

    // Initialize the WASM instance
    await wasmModule.default();

    const bindings = wrapWasmExports(wasmModule);
    wasmInstance = bindings;

    // Log SIMD status
    if (bindings.hasSimd()) {
      console.log('[WASM] SIMD128 acceleration enabled');
    } else {
      console.log('[WASM] SIMD128 not available, using scalar path');
    }

    return bindings;
  } catch (e) {
    console.warn('[WASM] Failed to initialize WASM module:', e);
    wasmInstance = null;
    return null;
  }
}

/**
 * Get the cached WASM bindings. Returns null if not initialized or unavailable.
 */
export function getWasmBindings(): WasmBindings | null {
  if (wasmInstance === undefined) {
    // Not initialized yet — caller should use initWasmBindings() first
    return null;
  }
  return wasmInstance;
}

/**
 * Check if WASM SIMD is available and initialized.
 */
export function isWasmSimdReady(): boolean {
  return wasmInstance?.hasSimd() ?? false;
}
