#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const wasmDir = path.join(__dirname, '..', 'webview', 'wasm');
const wasmPath = path.join(wasmDir, 'niftispy_wasm_bg.wasm');
const outPath = path.join(wasmDir, 'wasmBase64.ts');
const gluePath = path.join(wasmDir, 'niftispy_wasm.js');

if (!fs.existsSync(wasmPath)) {
  console.error('WASM file not found:', wasmPath);
  process.exit(1);
}

const wasmBytes = fs.readFileSync(wasmPath);
const base64 = wasmBytes.toString('base64');

const ts = `// Auto-generated by scripts/inline-wasm.js. Do not edit manually.
export const WASM_BASE64 = '${base64}';
`;

fs.writeFileSync(outPath, ts);
console.log(`Inlined ${wasmBytes.length} bytes of WASM into ${outPath}`);

// The wasm-pack glue uses import.meta.url as a fallback to locate the .wasm
// file. We inline the binary and call initSync, so this fallback is never
// reached. Replace it with a dummy URL to silence esbuild's IIFE warning.
if (fs.existsSync(gluePath)) {
  let glue = fs.readFileSync(gluePath, 'utf8');
  const original = glue;
  glue = glue.replace(/new URL\('niftispy_wasm_bg\.wasm', import\.meta\.url\)/g, "new URL('data:')");
  if (glue !== original) {
    fs.writeFileSync(gluePath, glue);
    console.log('Patched wasm-pack glue to avoid import.meta.url fallback.');
  }
}
