name: Release
on:
  push:
    tags: ['v*']

jobs:
  package-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: npm ci
      - run: npm run build
      - run: npx vsce package --no-dependencies
      - uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: '*.vsix'
